
CREATE TABLE PLAYLIST(
CODIGO VARCHAR2(20) PRIMARY KEY,
TITULO VARCHAR2(50),
NUMREPRODUCCIONES NUMBER(10),
DURACIONTOTAL NUMBER(10)
);

CREATE TABLE AUTOR(
CODIGO VARCHAR2(20) PRIMARY KEY,
NOMBRE VARCHAR2(50),
NOMBREARTISTICO VARCHAR2(50),
VERIFICADO NUMBER(1)
);

CREATE TABLE CANCION(
CODIGO_PLAYLIST VARCHAR2(20),
CODIGO_AUTOR VARCHAR2(20),
CODIGO VARCHAR2(20),
TITULO VARCHAR2(50),
DURACION NUMBER(5),
PUNTUACION NUMBER(5),
GENERO VARCHAR2(50),
CONSTRAINT PK_REPRODUCCION PRIMARY KEY (CODIGO_PLAYLIST, CODIGO_AUTOR),
CONSTRAINT FK1_REPRODUCCION FOREIGN KEY(CODIGO_PLAYLIST) REFERENCES PLAYLIST(CODIGO),
CONSTRAINT FK2_REPRODUCCION FOREIGN KEY(CODIGO_AUTOR) REFERENCES AUTOR(CODIGO)

);
SELECT * FROM AUTOR;

